dist: xenial
language: ruby
rvm:
- 2.6.5
before_script:
- echo -e "Host railsexpress.de\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- ssh-add ./deploy_key
- cat ./dockerhub-token | docker login -u stkaes --password-stdin
script: make -j 4 containers release publish
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_0b2cc28b3f02_key -iv $encrypted_0b2cc28b3f02_iv -in dockerhub-token.enc -out ./dockerhub-token -d
- openssl aes-256-cbc -K $encrypted_0b2cc28b3f02_key -iv $encrypted_0b2cc28b3f02_iv -in deploy_key.enc -out ./deploy_key -d
