dist: xenial
language: ruby
rvm:
- 2.6.5
before_script:
- docker pull buildpack-deps:bionic-scm
- docker pull buildpack-deps:xenial-scm
script: make container-bionic
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_0b2cc28b3f02_key -iv $encrypted_0b2cc28b3f02_iv -in deploy_key.enc -out ./deploy_key -d
- echo -e "Host railsexpress.de\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- ssh-add ./deploy_key
- ssh uploader@railsexpress.de pwd
