dist: bionic
language: ruby
rvm:
- 2.6.6
before_script:
- echo -e "Host railsexpress.de\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- eval "$(ssh-agent -s)"
- chmod 600 ./railsexpress-key
- ssh-add ./railsexpress-key
- cat ./docker-token | docker login -u stkaes --password-stdin
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_0b2cc28b3f02_key -iv $encrypted_0b2cc28b3f02_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
jobs:
  include:
    - name: focal
      script:
        - make container-focal package-focal push-focal publish-focal
    - name: bionic
      script:
        - make container-bionic package-bionic push-bionic publish-bionic
    - name: xenial
      script:
        - make container-xenial package-xenial push-xenial publish-xenial
    - name: focal-usr-local
      script:
        - make container-focal-usr-local package-focal-usr-local push-focal-usr-local publish-focal-usr-local
    - name: bionic-usr-local
      script:
        - make container-bionic-usr-local package-bionic-usr-local push-bionic-usr-local publish-bionic-usr-local
    - name: xenial-usr-local
      script:
        - make container-xenial-usr-local package-xenial-usr-local push-xenial-usr-local publish-xenial-usr-local
