dist: xenial
language: ruby
rvm:
- 2.6.5
before_script:
- echo -e "Host railsexpress.de\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- eval "$(ssh-agent -s)"
- chmod 600 ./railsexpress-key
- ssh-add ./railsexpress-key
- cat ./docker-token | docker login -u stkaes --password-stdin
script: make $TARGET
env:
  - TARGET=container-bionic package-bionic push-bionic publish
  - TARGET=container-xenial package-xenial push-xenial publish
  - TARGET=container-bionic-usr-local package-bionic-usr-local push-bionic-usr-local publish
  - TARGET=container-xenial-usr-local package-xenial-usr-local push-xenial-usr-local publish
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_0b2cc28b3f02_key -iv $encrypted_0b2cc28b3f02_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
